name: onnx2circom
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - ca-certificates=2023.5.7=h56e8100_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cudatoolkit=11.1.1=heb2d755_10
  - cudnn=8.2.1=cuda11.3_0
  - debugpy=1.5.1=py38hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - importlib_metadata=6.6.0=hd8ed1ab_0
  - ipykernel=6.15.0=pyh025b116_0
  - ipython=8.12.0=pyh08f2357_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py38haa244fe_0
  - libffi=3.4.2=hd77b12b_6
  - libsodium=1.0.18=h8d14728_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - openssl=1.1.1t=h2bbff1b_0
  - packaging=23.1=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.0.1=py38haa95532_0
  - platformdirs=3.2.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.0=py38h2bbff1b_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - python=3.8.16=h6244533_3
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pywin32=305=py38h2bbff1b_0
  - pyzmq=23.2.0=py38hd77b12b_0
  - rust=1.68.2=hf8d6059_1
  - rust-std-x86_64-pc-windows-msvc=1.68.2=h69312b4_1
  - setuptools=66.0.0=py38haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tornado=6.2=py38h294d835_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=py38haa95532_0
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - pip:
    - absl-py==1.4.0
    - astunparse==1.6.3
    - cachetools==5.3.0
    - certifi==2022.12.7
    - charset-normalizer==3.1.0
    - coloredlogs==15.0.1
    - contourpy==1.0.7
    - cycler==0.11.0
    - docopt==0.6.2
    - flatbuffers==2.0.7
    - fonttools==4.39.3
    - gast==0.4.0
    - google-auth==2.17.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.53.0
    - h5py==3.8.0
    - humanfriendly==10.0
    - idna==3.4
    - importlib-metadata==6.4.1
    - importlib-resources==5.12.0
    - jax==0.4.8
    - joblib==1.2.0
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - libclang==16.0.0
    - markdown==3.4.3
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - ml-dtypes==0.1.0
    - mpmath==1.3.0
    - numpy==1.23.4
    - oauthlib==3.2.2
    - onnx==1.10.0
    - onnxconverter-common==1.13.0
    - onnxruntime==1.14.1
    - opt-einsum==3.3.0
    - pandas==2.0.0
    - pillow==9.5.0
    - protobuf==3.19.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydot==1.4.2
    - pyparsing==3.0.9
    - pyreadline3==3.4.1
    - python-graphviz==0.20.1
    - python-version==0.0.2
    - pytz==2023.3
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.1.0
    - scipy==1.10.1
    - skl2onnx==1.14.0
    - sympy==1.11.1
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.10.0
    - tensorflow-addons==0.20.0
    - tensorflow-estimator==2.10.0
    - tensorflow-intel==2.12.0
    - tensorflow-io-gcs-filesystem==0.31.0
    - termcolor==2.2.0
    - tf2onnx==1.14.0
    - threadpoolctl==3.1.0
    - typeguard==2.13.3
    - typing==3.7.4.3
    - tzdata==2023.3
    - urllib3==1.26.15
    - werkzeug==2.2.3
    - wrapt==1.14.1
prefix:  ~/onnx2circom
